CREATE TABLE  dim_fare_class (
    FARE_CLASS_SK NUMBER(10),
    FARE_CLASS_ID NUMBER  ,
    FARE_CODE VARCHAR2(5),
    FARE_DESCRIPTION VARCHAR2(80),
    CABIN VARCHAR2(30),
    REFUNDABLE VARCHAR2(1),
    MILES_MULTIPLIER NUMBER(5,2),

    CONSTRAINT pk_dim_fare_class PRIMARY KEY (FARE_CLASS_SK)
);


CREATE TABLE  dim_routes (
    ROUTE_SK NUMBER(10),
    ROUTE_ID NUMBER  ,
    ORIGIN_AIRPORT_ID NUMBER ,
    DESTINATION_AIRPORT_ID NUMBER,
    DISTANCE_KM NUMBER,
    FLIGHT_DURATION_MIN NUMBER,
    IS_INTERNATIONAL VARCHAR2(1),
    BASE_PRICE_USD NUMBER(10,2),

    CONSTRAINT pk_dim_routes PRIMARY KEY (ROUTE_SK)
);

CREATE TABLE DIMAIRCRAFT (
    AIRCRAFT_KEY NUMBER PRIMARY KEY,
    AIRCRAFT_ID NUMBER,
    TAIL_NUMBER VARCHAR2(20),
    MODEL VARCHAR2(80),
    MANUFACTURER VARCHAR2(80)
);

CREATE TABLE DIM_AIRPORT (
    AIRPORT_KEY NUMBER PRIMARY KEY,
    AIRPORT_ID NUMBER,
    IATA_CODE VARCHAR2(3),
    AIRPORT_NAME VARCHAR2(120),
    CITY VARCHAR2(80),
    COUNTRY VARCHAR2(80),
    TIMEZONE VARCHAR2(80)
);

CREATE TABLE DIM_BOOKING_CHANNEL (
    CHANNEL_KEY NUMBER PRIMARY KEY,
    CHANNEL_ID NUMBER,
    CHANNEL_NAME VARCHAR2(50),
    CHANNEL_TYPE VARCHAR2(50),
    IS_ONLINE CHAR(1)
);

CREATE TABLE DIM_FLIGHT (
    FLIGHT_KEY NUMBER PRIMARY KEY,
    FLIGHT_ID NUMBER,
    FLIGHT_NUMBER VARCHAR2(10),
    ROUTE_KEY NUMBER,
    AIRCRAFT_KEY NUMBER,
    STATUS VARCHAR2(30)
);

CREATE TABLE DIM_PROMOTION (
    PROMOTION_KEY NUMBER PRIMARY KEY,
    PROMO_ID NUMBER,
    PROMO_CODE VARCHAR2(20),
    PROMO_NAME VARCHAR2(100),
    DISCOUNT_PCT NUMBER(5,2),
    MILES_BONUS NUMBER,
    START_DATE DATE,
    END_DATE DATE,
    IS_ACTIVE CHAR(1)
);

CREATE TABLE dim_date (
    Date_Key   NUMBER(8) NOT NULL,
    Full_Date  DATE NOT NULL,
    Day        NUMBER(2) NOT NULL,
    Month      NUMBER(2) NOT NULL,
    Quarter    NUMBER(1) NOT NULL,
    Year       NUMBER(4) NOT NULL,
    
    CONSTRAINT pk_dim_date PRIMARY KEY (Date_Key)
);

