CREATE TABLE  dim_fare_class (
    FARE_CLASS_SK NUMBER(10),
    FARE_CLASS_ID NUMBER  ,
    FARE_CODE VARCHAR2(5),
    FARE_DESCRIPTION VARCHAR2(80),
    CABIN VARCHAR2(30),
    REFUNDABLE VARCHAR2(1),
    MILES_MULTIPLIER NUMBER(5,2)
);

select * from dim_fare_class;



CREATE TABLE  dim_routes (
    ROUTE_SK NUMBER(10),
    ROUTE_ID NUMBER  ,
    ORIGIN_AIRPORT_ID NUMBER ,
    DESTINATION_AIRPORT_ID NUMBER,
    DISTANCE_KM NUMBER,
    FLIGHT_DURATION_MIN NUMBER,
    IS_INTERNATIONAL VARCHAR2(1),
    BASE_PRICE_USD NUMBER(10,2)
);

select * from dim_routes;